language: scala
sudo: false
# Cache settings here are based on latest SBT documentation.
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
# There's no nicer way to specify this matrix; see
# https://github.com/travis-ci/travis-ci/issues/1519.
matrix:
  include:
    # Scala 2.11 tests:
    - jdk: openjdk7
      scala: 2.11.7
      env: HADOOP_VERSION="2.8.0" SPARK_VERSION="2.4.0" AWS_JAVA_SDK_VERSION="1.11.160"

script:
  - ./dev/run-tests-travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
